### ISSUE TITLE
Help with Ruby Gems token

### ISSUE THREAD

**Issue by HassanAkbar** [ietf-ribose/tractive#113]
The workflow here (https://github.com/ietf-ribose/tractive/pull/112) is failing because of multi factor authentication is disabled for the `secrets.RIBOSE_CI_RUBYGEMS_API_KEY` account. 

@CAMOBAP Can you help here?

**Comment by CAMOBAP** [comment]
@HassanAkbar i'm not sure, I don't have access to generate api key for ribose organisation, I can only push gems. But I'm not sure you right about _"...  failing because of multi factor authentication is disabled ..."_

As far as I remember we had the same issue for `metanorma` and we was able to resolve it. I didn't remember exactly what we did but probably we just generated API key without MFA like shown here https://guides.rubygems.org/api-key-scopes/#enable-mfa-on-specific-api-keys

@ronaldtse could you please update `secrets.RIBOSE_CI_RUBYGEMS_API_KEY with disabled MFA

**Comment by CAMOBAP** [comment]
@ronaldtse friendly reminder

**Comment by ronaldtse** [comment]
I've done the necessary steps. Can you please try again?

**Comment by HassanAkbar** [comment]
@ronaldtse The issue has been fixed and a new version `1.0.26` has been released.
