### ISSUE TITLE
Investigate issue import API if we need any changes

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#17]
I suspect Octokit is good enough but these are also useful for a read:

* https://gist.github.com/jonmagic/5282384165e0f86ef105
* https://github.com/brucemiller/trac2issues/blob/master/trac2issues (from our good friend Bruce)

**Comment by HassanAkbar** [comment]
@ronaldtse 

I started implementing `Octokit` but I am facing 2 challenges while implementing it, 
1. There is no way to add comments to an issue while creating an issue.
2. There is no way to add multiple comments to an existing issue in a single API request.

These are not actually Octokit issues but are GitHub API v3 restrictions. In the existing implementation, we are using the old Github API which supports adding bulk comments to an issue (in issue creation API request).

**What we can do is** 
- Create an issue
- Add all comments in a loop

**Pros of this approach**
- We can easily link the replies of comments because the comment will already be created on GitHub.

**Cons with this approach**
- This will take more time in migration as there is an API limit on GitHub of 30 requests per minute.
- We will have to enhance our Error handling.

**Comment by HassanAkbar** [comment]
One more issue I faced while migrating to `Octokit` is that the comments created have a created date of when the script was run and not the date provided in the options. Should we go with `Octokit` and add the date in the comment or should we use the old API?

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar for the investigation and experimentation. It looks like at this time we should still stay with the Bulk Import API since `Octokit` / GitHub API v3 is unable to let us retain the original issue dates, and since we have to still use a fake user for importing.
