### ISSUE TITLE
Mapping of labels

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#27]
We need to ensure the labels are properly migrated.

For example, in this migration we see multiple `owner:` labels that don't make much sense.

<img width="914" alt="Screenshot 2021-08-31 at 6 08 23 PM" src="https://user-images.githubusercontent.com/11865/131488763-9bbc744f-e5b6-4baa-a5b4-b05a3a545641.png">

**Comment by HassanAkbar** [comment]
The owner mapping was also missing because of the mapping missing in the config file as explained in this [comment](https://github.com/ietf-ribose/tractive/issues/28#issuecomment-913623839).

I've mapped all the users to same user for testing and ran it once [here](https://github.com/hassanakbar4/tractive_test/issues) is the output. You can see that all the labels are now populating properly.

**Comment by ronaldtse** [comment]
Confirmed. Thanks @HassanAkbar !
