### ISSUE TITLE
Fix SVN reference in different formats

### ISSUE THREAD

**Issue by HassanAkbar** [ietf-ribose/tractive#61]
_@rcross@amsl.com_ _commented_

___
Fixed in [1066/mailarch]:

Optimize query for message.next_in_list(). Fixes #3137

_Originally posted by @HassanAkbar in https://github.com/ietf-svn-conversion/mailarchive/issues/3137#issuecomment-949480012_

`Fixed in [1066/mailarch]` this is currently not resolving to any commit SHA because of `/mailarch` postfix.

**Comment by ronaldtse** [comment]
Good find, I guess we need to migrate the data sources (repo vs tickets)...

**Comment by HassanAkbar** [comment]
@ronaldtse 
Right now, we are only resolving `[<any number>]` pattern for mapping SVN revision number to Git SHA.

I think we should do something like this in the regex `[<any number>/<anything>]`, and then extract the number and resolve it to a SHA hash using revmap file.

What do you suggest?

**Comment by ronaldtse** [comment]
> I think we should do something like this in the regex [<any number>/<anything>], and then extract the number and resolve it to a SHA hash using revmap file.

Agree. However, I don't know if in `[foo/bar]` the `foo` really always represents a commit.

**Comment by ronaldtse** [comment]
Pinging @rjsparks for an opinion.

**Comment by rjsparks** [comment]
It does. The construction here is due to mailarch being a separate svn repository being handled by the trac instance. it will always be [revision number/svn repository name]  where `/svn repository name` is left out if it was the primary repository for the trac instance ( unless someone entered nonsense manually, and I don't expect to run into that).

To be clear - in the example above, that's commit 1066 in the mailarch svn repository and has nothing to do with 1066 in the ietfdb svn repository,

If there's any confusion remaining, it might help to look at these through the production trac browser:

Look at https://trac.ietf.org/trac/ietfdb/browser, scroll to the bottom and note that the trac instance is attached to mailarch and mentoring in addition to ietfdb. We are not migrating mentoring - it is empty.

Look at https://trac.ietf.org/trac/ietfdb/ticket/3431 and note that the link at [1066/mailarch] takes you into the source browser for the mailarch svn repository, not the ietfdb repository. Specifically, contrast https://trac.ietf.org/trac/ietfdb/changeset/1162/mailarch with https://trac.ietf.org/trac/ietfdb/changeset/1162.

**Comment by rjsparks** [comment]
(I see I slipped off into looking at 3431 instead of 3137. I'll preserve 3431 here as an additional example, and edit the previous comment to match 3137 consistently.

Look at https://trac.ietf.org/trac/ietfdb/ticket/3431 and note that the link at [1162/mailarch] takes you into the source browser for the mailarch svn repository, not the ietfdb repository. Specifically, contrast https://trac.ietf.org/trac/ietfdb/changeset/1162/mailarch with https://trac.ietf.org/trac/ietfdb/changeset/1162.

**Comment by ronaldtse** [comment]
@rjsparks thanks. I hope it works -- the problem is that there may be a race condition if there happens to be a reference DAG cycle.

This works:
1. Suppose Repo A r1 refers to Repo B r1, then Repo B r2 refers to Repo A r2.
2. We first migrate both Repo A and Repo B to Git
3. We update the "Git commit from Repo A r1" with "Repo B r1's Git commit hash". Then, Repo A r1's and r2's Git commit hashes would have changed.
4. We then update Repo B r2 with Repo A r1's Git commit hash. Repo B r2 will be updated.

This contains a cycle:
1. Suppose Repo A r1 refers to Repo B r1, then Repo B r2 refers to Repo A r1.
2. We first migrate both Repo A and Repo B to Git
3. We update the "Git commit from Repo A r1" with "Repo B r1's Git commit hash". Then, Repo A r1's and r2's Git commit hashes would have changed.
4. We then update Repo B r1 and Repo B r2 with Repo A r1's Git commit hash. Then Repo B r1's and r2's Git commit hashes will be updated.
5. We're screwed.

**Comment by rjsparks** [comment]
(Being verbose in order to be specific with nouns):

I do not expect we will see any comments in commits to the ietfdb (datatracker) svn repository refer to svn commits in the mailarch repository, nor vice-versa.

I also don't expect to see any trac tickets in the ietfdb trac instance that would have references to both commits in the ietfdb svn repository and the mailarch svn repository - they will speak to one or the other, but even if there were, as above, the comments in commits in the svn repositories would not point across repositories.

So, I think the likelihood of running into the DAG cycle you describe is small.

**Comment by ronaldtse** [comment]
Thank you @rjsparks for the clarification, which is good news.

References in trac tickets won't be an issue, we can always finish migrating the Git commits and then use the revamps for Trac migration.

Fingers crossed there is no referential cycle...

The other challenge is to find out which SVN repositories form this referential network. The situation of Repo A and Repo B needs to be generalised across all repos.

Maybe the steps are to:
1. Find out what repos contain cross-repo references
2. Determine that there is no cycle
3. Determine the order of using rev-maps to update repos because there is a order dependency

@HassanAkbar does this sound reasonable?

**Comment by HassanAkbar** [comment]
@ronaldtse @rjsparks 
By using Github UI Search, I searched for following:
1. `mailarch` in ietfdb repo
2. `ietfdb` in mailarchive repo

I can’t seem to find any cross-repo references in commit messages and thats why there are no cycles as well.
Let me know if I need to verify any other repositories.
But I think this convention is mostly used in Issues. We don’t need to worry about commits at all there.
