### ISSUE TITLE
Wiki conversion: Convert WikiMedia internal links

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#77]
From @rjsparks:

> More importantly the internal links from this page to other wiki pages didn't get built - see`If so, please sign up on the [wiki:IETF110.1SprintSignUp] page.` for example.

https://trac.edgewall.org/wiki/WikiFormatting#Links

<img width="682" alt="image" src="https://user-images.githubusercontent.com/11865/146702356-ef91a1cd-4b28-40dc-99c9-7326be707f26.png">

_Originally posted by @rjsparks in https://github.com/ietf-ribose/github-migration-project/issues/12#issuecomment-996821485_

**Comment by HassanAkbar** [comment]
Currently, if there is a [CamelCase](https://trac.edgewall.org/wiki/CamelCase) word in `trac` it blindly turns it into a wiki link. 
Clicking on that link takes us to the wiki page if it exists otherwise it will take us to a page that states that the page does not exist and shows the option to create a page by the same name. 
But if we do the same in Github, the link will show a `404 not found` Github page if the wiki does not exist.

@rjsparks  should we only convert a [CamelCase](https://trac.edgewall.org/wiki/CamelCase) word which is a valid `wiki page` name in the database rather than converting the CamelCase word blindly to a link?

**Comment by rjsparks** [comment]
Yes, that's fine. I had commented about CamelCase elsewhere already. Be sure no to try to make links for camelcased words prefixed with a !.
